# Generated by Django 5.0.2 on 2024-04-26 01:08

import core.oauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_oauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationclient',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='applicationclient',
            name='redirect_uri',
        ),
        migrations.AlterField(
            model_name='applicationclient',
            name='client_id',
            field=models.CharField(default=core.oauth.models.generate_client_id, max_length=255, unique=True),
        ),
    ]
